SPLIT_KEYBOARD = yes

OLED_ENABLE = yes
OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes
AUDIO_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
QMK_SETTINGS = no
EXTRAKEY_ENABLE = yes
RGBLIGHT_ENABLE = no