name: Build LM40

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container: qmkfm/qmk_cli

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Compile LM40
      run: |
        git config --global --add safe.directory $(pwd)
        make git-submodule
        make anikodi/lm40:vial
    - name: Upload the generated hex file
      uses: actions/upload-artifact@v2
      with:
        name: hex_file
        path: anikodi_lm40_vial.hex
    - name: Download the hex file
      uses: actions/download-artifact@v2
      with:
        name: hex_file
