name: Build Void FRL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container: qmkfm/qmk_cli

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Compile Void FRL
      run: |
        make voidfrl:vial
    - name: Upload the generated hex file
      uses: actions/upload-artifact@v2
      with:
        name: hex_file
        path: coseyfannitutti_mysterium_via.hex
    - name: Download the hex file
      uses: actions/download-artifact@v2
      with:
        name: hex_file